---
title: The Master's University
timezone: UTC
collections:
  landingPageBanners:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: landingPageBanners
  values:
    description: ''
    image: ''
    link: ''
    title: Landing Page Banners
    output: false
email: your-email@domain.com
description: 'Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.'
baseurl: ''
url: https://blakenoll.github.io/TMU/
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
theme:
sass:
  style: compressed
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
