---
title: The Master's University
timezone: UTC
collections:
  admissions:
    title: Admissions
    output: true
  alumni:
    title: Alumni
    output: false
  performingarts:
    title: Arts
    output: true
  authors:
    title: Authors
    output: false
  campus-links:
    title: Campus Links
    output: true
  campus-ministries:
    title: Campus Ministries
    output: true
  categories:
    title: Catergories
    output: true
  conference-services:
    title: Conference Services
    output: true
  counselors:
    title: Counselors
    output: true
  departments:
    title: Departments
    output: true
  dorms:
    title: Dorms
    output: true
  faculty:
    title: Faculty
    output: true
  financialaid:
    title: Financial Aid
    output: true
  give:
    title: Give
    output: true
  gradprograms:
    title: Grad-Programs
    output: true
  landingPageBanners:
    title: Landing Page Banners
    output: true
  onlineprograms:
    title: Online Programs
    output: true
  posts:
    title: Posts
    output: true
  redirects:
    title: Redirects
    output: true
  student-advancment:
    title: Student Advancment
    output: true
  studentlife:
    title: Student Life
    output: true
  upcomingevents:
    title: Upcoming Events
    output: true
  uploads:
    title: Uploads
    output: true
  adjunct-faculty:
    title: adjunct-faculty
    output: true
  library:
    title: library
    output: true
  outreach:
    title: outreach
    output: true
  undergrad-admissions:
    title: undergrad admissions
    output: true
    permalink: "/admissions/undergrad/:path"
  visit:
    title: visit
    output: true
defaults:
- scope:
    path: ''
    type: admissions
  values:
    permalink: "/admissions/#:title"
- scope:
    path: ''
    type: conference-services
  values:
    layout: confserv
- scope:
    path: ''
    type: landingPageBanners
  values:
    description: ''
    image: ''
    link: ''
    title: ''
    button-text: ''
    end-date: ''
- scope:
    path: ''
    type: upcomingevents
  values:
    title: ''
    image: ''
    event_date: ''
    event-link: ''
    description: ''
    permalink: "/upcomingevents/:title"
- scope:
    path: ''
    type: posts
  values:
    layout: news
    title: ''
    author: ''
    catergory: ''
    image: ''
    sm-image: ''
    permalink: "/news/:title.html"
- scope:
    path: ''
    type: departments
  values:
    layout: undergradmajor
    title: ''
    sm-image: ''
    description: ''
    emphasis:
    -
    -
    total-credits: ''
    bible-credits: ''
    GE-credits: ''
    core-courses: ''
    emphasis-electives: ''
    course-offerings:
    -
    -
    careers:
    -
    -
    why-at-masters-body: ''
    quote: ''
    required-courses-body: ''
    prof-publications-body: ''
    permalink: "/academics/undergraduate/:title"
- scope:
    path: ''
    type: dorms
  values:
    layout: dorm
    image: ''
    permalink: "/:title"
    ra:
    - name: ''
      title: ''
      body-text: ''
- scope:
    path: ''
    type: gradprograms
  values:
    layout: gradprogram
    title: ''
    sm-image: ''
    program-outline-text: ''
    courses-body:
    -
    permalink: "/academics/graduate/:title"
- scope:
    path: ''
    type: onlineprograms
  values:
    layout: onlineprogram
    title: ''
    sm-image: ''
    permalink: "/academics/online/:title"
- scope:
    path: ''
    type: faculty
  values:
    layout: faculty
    title: ''
    permalink: faculty/:title
    job-title: ''
    image: ''
    department: ''
    grad-program: ''
    degrees:
    -
    -
    email: ''
- scope:
    path: ''
    type: authors
  values:
    title: ''
    image: ''
    twitter: ''
    medium: ''
- scope:
    path: ''
    type: studentlife
  values:
    sm-image: ''
    permalink: "/studentlife/:title"
- scope:
    path: ''
    type: campus-links
  values:
    permalink: "/:title/"
- scope:
    path: ''
    type: categories
  values:
    layout: categories
    permalink: "/news/:title"
- scope:
    path: ''
    type: counselors
  values:
    layout: counselor
    permalink: "/admissions/:title"
    name: ''
    email: ''
    phone: ''
    video: ''
- scope:
    path: ''
    type: give
  values:
    layout: give
    permalink: "/give/:title"
- scope:
    path: ''
    type: financialaid
  values:
    sm-image: ''
    layout: financialaid
    permalink: "/financial-aid/:title"
- scope:
    path: ''
    type: redirects
  values:
    permalink: "/:title"
    redirect_to: ''
    layout: redirect
- scope:
    path: ''
    type: adjunct-faculty
  values:
    image: ''
    department: ''
    job-title: ''
    degrees:
    -
    layout: adjunctfaculty
email: your-email@domain.com
description: Under the leadership of president Dr. John MacArthur, The Master's University
  provides quality education both on campus and through online distance education.
url: "//www.masters.edu"
baseurl:
amazonurl: http://themastersuniv.s3-website-us-west-1.amazonaws.com
githuburl: https://blakenoll.github.io/TMU
twitter_username: mastersuniv
github_username: jekyll
default_img: "/images/TMU_Logo_200x100-01.png"
google_analytics: UA-2614423-3
markdown: kramdown
tipue_search:
  include:
    pages: true
    collections:
    - undergrad-admissions
    - departments
    - gradprograms
    - studentlife
    - faculty
    - give
    - financialaid
    - campus-links
    - admissions
    - performingarts
    - onlineprograms
    - counselors
    - outreach
    - student-advancment
theme:
paginate: 12
paginate_path: "/news/page:num/"
sass:
  style: compressed
plugins:
- jekyll-feed
- jekyll-redirect-from
- jekyll-paginate
exclude:
- Gemfile
- Gemfile.lock
- "/node_modules"
